//! Small numeric helpers whose only job is to behave exactly like Python's.
//!
//! These exist because the reference implementation was Python and the golden
//! fixtures were generated by it. Two of Python's arithmetic behaviours differ
//! from Rust's defaults in ways that would silently move a censor box.

/// Python's `//`: floor division, rounding toward negative infinity.
///
/// Rust's `/` truncates toward zero, so `-3 / 2 == -1` while Python's
/// `-3 // 2 == -2`. This matters in `build_graph`, where a window narrower
/// than the shared crop box produces a negative `(w - bw) // 2` on the way to
/// recentring it. Truncating there would shift the cover by a pixel.
pub fn floor_div(a: i64, b: i64) -> i64 {
    debug_assert!(b != 0, "floor_div by zero");
    let q = a / b;
    if (a % b != 0) && ((a < 0) != (b < 0)) {
        q - 1
    } else {
        q
    }
}

/// Python's `round(x, 3)`: correctly rounded to three decimals, ties to even.
///
/// Formatting to three decimals and parsing back gives exactly that, and it is
/// the same rounding the value would receive again when the filtergraph is
/// written out with `{:.3}`. Doing it here keeps the stored window boundaries
/// identical to the ones the Python engine recorded.
pub fn round3(x: f64) -> f64 {
    format!("{x:.3}").parse().unwrap_or(x)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn floor_div_matches_python_on_negatives() {
        // The cases Rust's `/` would get wrong.
        assert_eq!(floor_div(-3, 2), -2);
        assert_eq!(floor_div(-1, 2), -1);
        assert_eq!(floor_div(-4, 2), -2);
        assert_eq!(floor_div(-512, 2), -256);
        // And the cases it would get right.
        assert_eq!(floor_div(3, 2), 1);
        assert_eq!(floor_div(0, 2), 0);
        assert_eq!(floor_div(512, 2), 256);
    }

    #[test]
    fn round3_matches_python() {
        // Values verified against the reference implementation's interpreter,
        // not assumed. `2.0005` and `1.0005` land on opposite sides because
        // neither is exactly representable, and the rounding is applied to the
        // actual binary value rather than the decimal literal.
        assert_eq!(round3(855.6666666666666), 855.667);
        assert_eq!(round3(2.0005), 2.001); // exact value is just above
        assert_eq!(round3(1.0005), 1.0); // exact value is just below
        assert_eq!(round3(1.0), 1.0);
        assert_eq!(round3(3697.0), 3697.0);
        // An exact tie, which must resolve to even rather than away from zero.
        assert_eq!(round3(0.0625), 0.062);
        assert_eq!(round3(0.125), 0.125);
    }
}
